apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon
  annotations:
    fluxcd.io/automated: "true"
  labels:
    app: beacon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beacon
  template:
    metadata:
      labels:
        app: beacon
    spec:
      containers:
        - name: beacon
          image: onlydole/beacon:1.19.1
          ports:
            - containerPort: 80
